=== 创建一个索引

到目前为止, 我们已经通过索引一篇文档创建了一个新的索引 ((("indices", "creating"))) 。这个索引采用的是默认的配置，新的字段通过动态映射的方式被添加到类型映射。现在我们需要对这个建立索引的过程做更多的控制：我们想要确保这个索引有数量适中的主分片，并且在我们索引任何数据 _之前_ ，分析器和映射已经被建立好。

为了达到这个目的，我们需要手动创建索引，在请求体里面传入设置或类型映射，如下所示：

[source,js]
--------------------------------------------------
PUT /my_index
{
    "settings": { ... any settings ... },
    "mappings": {
        "type_one": { ... any mappings ... },
        "type_two": { ... any mappings ... },
        ...
    }
}
--------------------------------------------------


实际上，如果你想，你 ((("indices", "preventing automatic creation of"))) 可以通过在 `config/elasticsearch.yml` 的每个节点下添加下面的配置，来禁止自动创建索引：

[source,js]
--------------------------------------------------
action.auto_create_index: false
--------------------------------------------------

[NOTE]
====
我们会在之后讨论你怎么用 <<index-templates>> 来重新配置开启自动创建索引。这在索引日志数据的时候尤其有用：你登入名字包括日期的一个索引，当半夜的 rolls 结束, 一个被合适配置的索引会自动出现。
====

=== 删除一个索引

用 ((("HTTP methods", "DELETE")))((("DELETE method", "deleting indices")))((("indices", "deleting"))) 删除一个索引:

[source,js]
--------------------------------------------------
DELETE /my_index
--------------------------------------------------


你可以这样删除多个索引：

[source,js]
--------------------------------------------------
DELETE /index_one,index_two
DELETE /index_*
--------------------------------------------------


你可以这样删除 _全部_ 索引：

[source,js]
--------------------------------------------------
DELETE /_all
DELETE /*
--------------------------------------------------

[NOTE]
====
对一些人来说，能够用单个命令来删除所有数据可能会导致可怕的后果。如果你想要避免意外的大量删除, 你可以在你的 `elasticsearch.yml` 做如下配置：

`action.destructive_requires_name: true`

这限制了只删除特定名称指向的数据, 而不允许删除特殊的 `_all` 和使用通配符指定数据。你同样可以通过 <<_changing_settings_dynamically, Cluster State API>> 动态地更新这个设置。


====
